/**
 * Apple Splash Screens Component
 *
 * Renders all necessary <link rel="apple-touch-startup-image"> tags for iOS PWA.
 * These provide launch images when the app is opened from home screen.
 *
 * Generated using: npx pwa-asset-generator ./public/icons/icon-512.png ./public/splash --splash-only --type png --background "#0A0A0A"
 *
 * @see https://developer.apple.com/design/human-interface-guidelines/app-icons
 */
export default function AppleSplashScreens() {
  // Splash screens generated by pwa-asset-generator
  const splashScreens = [
    // iPad Pro 12.9"
    { href: '/splash/apple-splash-2048-2732.png', media: '(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
    { href: '/splash/apple-splash-2732-2048.png', media: '(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
    // iPad Pro 11"
    { href: '/splash/apple-splash-1668-2388.png', media: '(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
    { href: '/splash/apple-splash-2388-1668.png', media: '(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
    // iPad 9.7"
    { href: '/splash/apple-splash-1536-2048.png', media: '(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
    { href: '/splash/apple-splash-2048-1536.png', media: '(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
    // iPad Air 10.9"
    { href: '/splash/apple-splash-1640-2360.png', media: '(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
    { href: '/splash/apple-splash-2360-1640.png', media: '(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
    // iPad Pro 10.5"
    { href: '/splash/apple-splash-1668-2224.png', media: '(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
    { href: '/splash/apple-splash-2224-1668.png', media: '(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
    // iPad 10.2"
    { href: '/splash/apple-splash-1620-2160.png', media: '(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
    { href: '/splash/apple-splash-2160-1620.png', media: '(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
    // iPad Mini 8.3"
    { href: '/splash/apple-splash-1488-2266.png', media: '(device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
    { href: '/splash/apple-splash-2266-1488.png', media: '(device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
    // iPhone 16 Pro Max
    { href: '/splash/apple-splash-1320-2868.png', media: '(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
    { href: '/splash/apple-splash-2868-1320.png', media: '(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)' },
    // iPhone 16 Pro
    { href: '/splash/apple-splash-1206-2622.png', media: '(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
    { href: '/splash/apple-splash-2622-1206.png', media: '(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)' },
    // iPhone 16 Plus, 15 Plus, 15 Pro Max, 14 Pro Max
    { href: '/splash/apple-splash-1260-2736.png', media: '(device-width: 420px) and (device-height: 912px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
    { href: '/splash/apple-splash-2736-1260.png', media: '(device-width: 420px) and (device-height: 912px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)' },
    // iPhone 15 Pro Max, 14 Pro Max
    { href: '/splash/apple-splash-1290-2796.png', media: '(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
    { href: '/splash/apple-splash-2796-1290.png', media: '(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)' },
    // iPhone 16, 15, 15 Pro, 14 Pro
    { href: '/splash/apple-splash-1179-2556.png', media: '(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
    { href: '/splash/apple-splash-2556-1179.png', media: '(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)' },
    // iPhone 14, 13, 13 Pro, 12, 12 Pro
    { href: '/splash/apple-splash-1170-2532.png', media: '(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
    { href: '/splash/apple-splash-2532-1170.png', media: '(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)' },
    // iPhone 14 Plus, 13 Pro Max, 12 Pro Max
    { href: '/splash/apple-splash-1284-2778.png', media: '(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
    { href: '/splash/apple-splash-2778-1284.png', media: '(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)' },
    // iPhone 13 Mini, 12 Mini, 11 Pro, XS, X
    { href: '/splash/apple-splash-1125-2436.png', media: '(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
    { href: '/splash/apple-splash-2436-1125.png', media: '(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)' },
    // iPhone 11 Pro Max, XS Max
    { href: '/splash/apple-splash-1242-2688.png', media: '(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
    { href: '/splash/apple-splash-2688-1242.png', media: '(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)' },
    // iPhone 11, XR
    { href: '/splash/apple-splash-828-1792.png', media: '(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
    { href: '/splash/apple-splash-1792-828.png', media: '(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
    // iPhone 8 Plus, 7 Plus, 6s Plus
    { href: '/splash/apple-splash-1242-2208.png', media: '(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
    { href: '/splash/apple-splash-2208-1242.png', media: '(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)' },
    // iPhone SE 2/3, 8, 7, 6s
    { href: '/splash/apple-splash-750-1334.png', media: '(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
    { href: '/splash/apple-splash-1334-750.png', media: '(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
    // iPhone SE 1, 5s
    { href: '/splash/apple-splash-640-1136.png', media: '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
    { href: '/splash/apple-splash-1136-640.png', media: '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
  ];

  return (
    <>
      {splashScreens.map((screen, index) => (
        <link
          key={index}
          rel="apple-touch-startup-image"
          href={screen.href}
          media={screen.media}
        />
      ))}
    </>
  );
}
